## 1. Import Libraries

In [35]:
import numpy as np
import pandas as pd

print('NumPy version:', np.__version__)
print('Pandas version:', pd.__version__)

NumPy version: 2.5.1
Pandas version: 2.3.3

In [36]:
# 1D and 2D array creation
arr_1d = np.array([10, 20, 30, 40, 50])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print('1D array:', arr_1d)
print('2D array:\n', arr_2d)

print('Shape:', arr_2d.shape)
print('Dtype:', arr_2d.dtype)
print('Ndim:', arr_2d.ndim)

# Indexing and slicing
print('First 3 elements:', arr_1d[:3])
print('Element at row 1, col 2:', arr_2d[1, 2])

1D array: [10 20 30 40 50]
2D array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dtype: int64
Ndim: 2
First 3 elements: [10 20 30]
Element at row 1, col 2: 6

## 3. Broadcasting

Broadcasting lets NumPy perform operations on arrays of different shapes.

In [37]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

# Adding a (1,3) array to a (3,1) array -> broadcasts to (3,3)
result = a + b
print(result)

# Scalar broadcasting
scaled = arr_1d * 2
print('Scaled array:', scaled)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
Scaled array: [ 20  40  60  80 100]

## 4. Pandas DataFrame Basics

In [38]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, np.nan, 22, 28],
    'Department': ['HR', 'IT', 'IT', 'Finance', np.nan],
    'Salary': [50000, 65000, 60000, np.nan, 72000]
}

df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  65000.0
2  Charlie   NaN         IT  60000.0
3    David  22.0    Finance      NaN
4      Eva  28.0        NaN  72000.0

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         4 non-null      float64
 2   Department  4 non-null      object
 3   Salary      4 non-null      float64
dtypes: float64(2), object(2)
memory usage: 292.0+ bytes

In [40]:
df.describe()

         Age        Salary
count   4.00      4.000000
mean   26.25  61750.000000
std     3.50   9251.126058
min    22.00  50000.000000
25%    24.25  57500.000000
50%    26.50  62500.000000
75%    28.50  66750.000000
max    30.00  72000.000000

In [41]:
data = {
    "Name":["John","Alice","Bob"],
    "Age":[24,30,28],
    "Salary":[50000,70000,60000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Salary
0   John   24   50000
1  Alice   30   70000
2    Bob   28   60000

In [42]:
print(df.head())

print(df.tail())

print(df.info())

print(df.describe())

    Name  Age  Salary
0   John   24   50000
1  Alice   30   70000
2    Bob   28   60000
    Name  Age  Salary
0   John   24   50000
1  Alice   30   70000
2    Bob   28   60000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None
             Age   Salary
count   3.000000      3.0
mean   27.333333  60000.0
std     3.055050  10000.0
min    24.000000  50000.0
25%    26.000000  55000.0
50%    28.000000  60000.0
75%    29.000000  65000.0
max    30.000000  70000.0

## 5. Reading Data from CSV / Excel / JSON

Below are the standard commands used to read data. A sample CSV is created first so the read_csv example is runnable end-to-end.

In [43]:
# Save the sample DataFrame to CSV so we can demonstrate reading it back
df.to_csv('sample_data.csv', index=False)

# Reading CSV
df_csv = pd.read_csv('sample_data.csv')
df_csv

    Name  Age  Salary
0   John   24   50000
1  Alice   30   70000
2    Bob   28   60000

In [44]:
# Reading Excel (requires openpyxl)
# df_excel = pd.read_excel('sample_data.xlsx')

# Reading JSON
df.to_json('sample_data.json', orient='records')
df_json = pd.read_json('sample_data.json')
df_json

    Name  Age  Salary
0   John   24   50000
1  Alice   30   70000
2    Bob   28   60000

In [45]:
import numpy as np
import pandas as pd

# Sample Dataset
data = {
    "Name": ["John", "Alice", "Bob", "John", None],
    "Age": [23, np.nan, 28, 23, 30],
    "Salary": [50000, 60000, np.nan, 50000, 70000],
    "Department": ["IT", "HR", "IT", "IT", "Sales"]
}

df = pd.DataFrame(data)

print("Original Dataset")
print(df)

# Remove duplicates
df.drop_duplicates(inplace=True)

# Fill missing values
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Salary"] = df["Salary"].fillna(df["Salary"].median())
df["Name"] = df["Name"].fillna("Unknown")

# Feature Engineering
df["Salary_Lakh"] = df["Salary"] / 100000
df["Bonus"] = df["Salary"] * 0.10
df["Age_Group"] = df["Age"].apply(lambda x: "Young" if x < 30 else "Adult")

print("\nCleaned Dataset")
print(df)

print("\nAverage Salary by Department")
print(df.groupby("Department")["Salary"].mean())

# Save cleaned dataset
df.to_csv("cleaned_dataset.csv", index=False)

Original Dataset
    Name   Age   Salary Department
0   John  23.0  50000.0         IT
1  Alice   NaN  60000.0         HR
2    Bob  28.0      NaN         IT
3   John  23.0  50000.0         IT
4   None  30.0  70000.0      Sales

Cleaned Dataset
      Name   Age   Salary Department  Salary_Lakh   Bonus Age_Group
0     John  23.0  50000.0         IT          0.5  5000.0     Young
1    Alice  27.0  60000.0         HR          0.6  6000.0     Young
2      Bob  28.0  60000.0         IT          0.6  6000.0     Young
4  Unknown  30.0  70000.0      Sales          0.7  7000.0     Adult

Average Salary by Department
Department
HR       60000.0
IT       55000.0
Sales    70000.0
Name: Salary, dtype: float64

In [46]:
employee_data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["John", "Alice", "Bob", "David", None, "Frank", "Grace", "Henry", "Ivy", "John"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR", "Finance", "Sales", "IT", "IT"],
    "Age": [25, 32, np.nan, 41, 27, 35, 31, np.nan, 29, 25],
    "Salary": [45000, 70000, 55000, 90000, np.nan, 65000, 72000, 52000, 58000, 45000],
    "Experience": [2, 8, 5, 15, 3, 10, 7, 1, 4, 2]
}

df = pd.DataFrame(employee_data)

print(df)

   Employee_ID   Name Department   Age   Salary  Experience
0          101   John         IT  25.0  45000.0           2
1          102  Alice         HR  32.0  70000.0           8
2          103    Bob    Finance   NaN  55000.0           5
3          104  David         IT  41.0  90000.0          15
4          105   None      Sales  27.0      NaN           3
5          106  Frank         HR  35.0  65000.0          10
6          107  Grace    Finance  31.0  72000.0           7
7          108  Henry      Sales   NaN  52000.0           1
8          109    Ivy         IT  29.0  58000.0           4
9          110   John         IT  25.0  45000.0           2

In [47]:
print(df[df["Age"] > 30])
print(df[df["Salary"] > 60000])
print(df[df["Department"] == "IT"])
print(df[(df["Age"] > 30) & (df["Salary"] > 60000)])

   Employee_ID   Name Department   Age   Salary  Experience
1          102  Alice         HR  32.0  70000.0           8
3          104  David         IT  41.0  90000.0          15
5          106  Frank         HR  35.0  65000.0          10
6          107  Grace    Finance  31.0  72000.0           7
   Employee_ID   Name Department   Age   Salary  Experience
1          102  Alice         HR  32.0  70000.0           8
3          104  David         IT  41.0  90000.0          15
5          106  Frank         HR  35.0  65000.0          10
6          107  Grace    Finance  31.0  72000.0           7
   Employee_ID   Name Department   Age   Salary  Experience
0          101   John         IT  25.0  45000.0           2
3          104  David         IT  41.0  90000.0          15
8          109    Ivy         IT  29.0  58000.0           4
9          110   John         IT  25.0  45000.0           2
   Employee_ID   Name Department   Age   Salary  Experience
1          102  Alice         HR  32.0  70000.0           8
3          104  David         IT  41.0  90000.0          15
5          106  Frank         HR  35.0  65000.0          10
6          107  Grace    Finance  31.0  72000.0           7

In [48]:
print(df.groupby("Department")["Salary"].mean())
print(df.groupby("Department")["Salary"].max())
print(df.groupby("Department")["Salary"].agg(["mean", "max", "min", "count"]))
print(df.groupby("Department")["Employee_ID"].count())

Department
Finance    63500.0
HR         67500.0
IT         59500.0
Sales      52000.0
Name: Salary, dtype: float64
Department
Finance    72000.0
HR         70000.0
IT         90000.0
Sales      52000.0
Name: Salary, dtype: float64
               mean      max      min  count
Department
Finance     63500.0  72000.0  55000.0      2
HR          67500.0  70000.0  65000.0      2
IT          59500.0  90000.0  45000.0      4
Sales       52000.0  52000.0  52000.0      1
Department
Finance    2
HR         2
IT         4
Sales      2
Name: Employee_ID, dtype: int64

In [49]:
print(df.isnull())
print(df.isnull().sum())
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Name"] = df["Name"].fillna("Unknown")

   Employee_ID   Name  Department    Age  Salary  Experience
0        False  False       False  False   False       False
1        False  False       False  False   False       False
2        False  False       False   True   False       False
3        False  False       False  False   False       False
4        False   True       False  False    True       False
5        False  False       False  False   False       False
6        False  False       False  False   False       False
7        False  False       False   True   False       False
8        False  False       False  False   False       False
9        False  False       False  False   False       False
Employee_ID    0
Name           1
Department     0
Age            2
Salary         1
Experience     0
dtype: int64

In [50]:
print(df.isnull().sum())

Employee_ID    0
Name           0
Department     0
Age            0
Salary         1
Experience     0
dtype: int64

In [51]:
df.drop_duplicates(inplace=True)

print(df)

df.rename(columns={"Salary": "Monthly_Salary"}, inplace=True)

print(df.head())

df["Age"] = df["Age"].astype(int)

print(df.dtypes)

df.sort_values(by="Monthly_Salary", ascending=False, inplace=True)

print(df)

   Employee_ID     Name Department     Age   Salary  Experience
0          101     John         IT  25.000  45000.0           2
1          102    Alice         HR  32.000  70000.0           8
2          103      Bob    Finance  30.625  55000.0           5
3          104    David         IT  41.000  90000.0          15
4          105  Unknown      Sales  27.000      NaN           3
5          106    Frank         HR  35.000  65000.0          10
6          107    Grace    Finance  31.000  72000.0           7
7          108    Henry      Sales  30.625  52000.0           1
8          109      Ivy         IT  29.000  58000.0           4
9          110     John         IT  25.000  45000.0           2
   Employee_ID     Name Department     Age  Monthly_Salary  Experience
0          101     John         IT  25.000         45000.0           2
1          102    Alice         HR  32.000         70000.0           8
2          103      Bob    Finance  30.625         55000.0           5
3          104    David         IT  41.000         90000.0          15
4          105  Unknown      Sales  27.000             NaN           3
Employee_ID         int64
Name               object
Department         object
Age                 int64
Monthly_Salary    float64
Experience          int64
dtype: object
   Employee_ID     Name Department  Age  Monthly_Salary  Experience
3          104    David         IT   41         90000.0          15
6          107    Grace    Finance   31         72000.0           7
1          102    Alice         HR   32         70000.0           8
5          106    Frank         HR   35         65000.0          10
8          109      Ivy         IT   29         58000.0           4
2          103      Bob    Finance   30         55000.0           5
7          108    Henry      Sales   30         52000.0           1
0          101     John         IT   25         45000.0           2
9          110     John         IT   25         45000.0           2
4          105  Unknown      Sales   27             NaN           3

In [52]:
df["Salary_Lakh"] = df["Monthly_Salary"] / 100000
df["Annual_Salary"] = df["Monthly_Salary"] * 12
df["Bonus"] = df["Monthly_Salary"] * 0.10
df["Age_Group"] = df["Age"].apply(
    lambda x: "Young" if x < 30 else "Adult"
)

print(df)

   Employee_ID     Name Department  Age  Monthly_Salary  Experience  \
3          104    David         IT   41         90000.0          15
6          107    Grace    Finance   31         72000.0           7
1          102    Alice         HR   32         70000.0           8
5          106    Frank         HR   35         65000.0          10
8          109      Ivy         IT   29         58000.0           4
2          103      Bob    Finance   30         55000.0           5
7          108    Henry      Sales   30         52000.0           1
0          101     John         IT   25         45000.0           2
9          110     John         IT   25         45000.0           2
4          105  Unknown      Sales   27             NaN           3

   Salary_Lakh  Annual_Salary   Bonus Age_Group
3         0.90      1080000.0  9000.0     Adult
6         0.72       864000.0  7200.0     Adult
1         0.70       840000.0  7000.0     Adult
5         0.65       780000.0  6500.0     Adult
8         0.58       696000.0  5800.0     Young
2         0.55       660000.0  5500.0     Adult
7         0.52       624000.0  5200.0     Adult
0         0.45       540000.0  4500.0     Young
9         0.45       540000.0  4500.0     Young
4          NaN            NaN     NaN     Young